### ISSUE TITLE
New Module: EarthAndMoon

### ISSUE THREAD

**Issue by joelman** [mykle1/MMM-EARTH#10]
Great work on your module; I love it.  But I also love the [Moon Phases Module](https://github.com/spectroman/mmm-moon-phases).  So I came up with an idea of how to combine them. [Earth and Moon](https://github.com/joelman/MMM-EarthAndMoon) toggles between earth and moon at sunrise and sunset.  Please give it a try and let me know what you think!

There are sample config values in the code.

Joel

**Comment by mykle1** [comment]
Thanks, but I also wrote a moon module some time ago called MMM-Lunartic. It's nothing special but it does give me satisfaction. I'm glad you liked MMM-Earth enough to use it. It was one of my very first modules and I still have it on my first mirror. MMM-Lunartic uses my very own API for the data so it's rather special to me

**Comment by joelman** [comment]
Oh, this isn't a moon module, it's just a module that transitions between the earth and moon modules at sunrise and sunset.
