### ISSUE TITLE
continuously loading

### ISSUE THREAD

**Issue by Antgr36** [mykle1/MMM-EARTH#11]
MMM-EARTH after the last update (today) is continuously loading. I tried uninstall and reinstall but I have the same results.
pm2 logs:
```0|mm       | Connecting socket for: MMM-NOAA3
0|mm       | Connecting socket for: MMM-Cocktails
0|mm       | Starting node_helper for: MMM-Cocktails
0|mm       | Connecting socket for: MMM-History
0|mm       | Starting module: MMM-History
0|mm       | Connecting socket for: newsfeed
0|mm       | Starting module: newsfeed
0|mm       | Sockets connected & modules started ...
0|mm       | Launching application.
0|mm       | https://epic.gsfc.nasa.gov/api/enhanced
0|mm       | Create new calendar fetcher for url: http://www.calendarlabs.com/ical-calendar/ics/47/Greece_Holidays.ics - Interval: 300000
0|mm       | ds
0|mm       | 1549195255
0|mm       | Create new news fetcher for url: https://www.newsbeast.gr/greece/feed - Interval: 300000
0|mm       | Create new news fetcher for url: https://www.news.gr/home/article-useful/23946/rss-feed.html - Interval: 300000```

**Comment by Antgr36** [comment]
But when I run ```npm start dev``` I get this error:
MMM-EARTH.js:95 Uncaught (in promise) TypeError: earthPhoto.classList.Add is not a function
    at Class.getDom (MMM-EARTH.js:95)
    at main.js:110
    at new Promise (<anonymous>)
    at updateDom (main.js:109)
    at Object.updateDom (main.js:514)
    at Class.updateDom (module.js:358)
    at rotateInterval.setInterval (MMM-EARTH.js:158)

**Comment by mykle1** [comment]
Sorry for the interruption to the module. The NASA API was having issues causing sporadic outages. Obviously, the module failed during those times. It is working again. Thank.
