### ISSUE TITLE
Module keeps on loading with "Hello Mother Earth"

### ISSUE THREAD

**Issue by martinkooij** [mykle1/MMM-EARTH#12]
I use mode "Natural" and varied on config.js, used the simplest version but behavior is always the same, no EARTH. This is since about two weeks (I can't remember the exact day). 

The problems showed both with and without updating. Also I did a fresh reinstall of the modules, both on the mirror and on my windows development machine. All the same behavior. 
 
The development tools in the browser show:

MMM-EARTH.js:90 Uncaught (in promise) TypeError: Cannot read property 'slice' of null
    at Class.getDom (MMM-EARTH.js:90)
    at main.js:110
    at new Promise (<anonymous>)
    at updateDom (main.js:109)
    at Object.updateDom (main.js:514)
    at Class.updateDom (module.js:358)
    at rotateInterval.setInterval (MMM-EARTH.js:158)

**Comment by martinkooij** [comment]
And I found the culprit. The date returned by the NASA API now "null"!!! That doesn.t help when slicing the date. Luckily for each photo the API returns an identifier that starts with the date. I sliced this one, and now it works again (for some time). 

I commented out two lines, added one and changed the definition of "daily". 
After that all worked. I didn't check if it does for all libraries... It does for "Natural" Does that help finding the issue Mykle1? 

            //const slicer = earth.date.slice(0, 10);   // Removed the culprit
            //const parts = slicer.split("-"); //NASA has set date to null so this doesn't work
	   const ident = earth.identifier;   
	   const daily = ident.slice(0,4) + "/" + ident.slice(4,6) + "/" + ident.slice(6,8); // get date from the identifier

**Comment by mykle1** [comment]
The entire issue was and is caused by the sporadic reliability of the API. Yes, all the things you described were symptoms of the API being down. For the past 2 years this API has been rock solid. Only recently are they having some issues. I apologize for the interruptions to the module but it is working again

**Comment by IceT-max** [comment]
I've installed the module but I've the same issue.. any ideas?
