### ISSUE TITLE
Update 

### ISSUE THREAD

**Issue by pociorotto** [mykle1/MMM-EARTH#13]
Hi ... The globe hasn't updated anymore for a while ... What happened?

**Comment by pociorotto** [comment]
Hi ... The globe hasn't updated anymore for a while ... What happened?

**Comment by pociorotto** [comment]
The module no longer updates ....

**Comment by mykle1** [comment]
Sorry it took so long to get back to you. I assume the api was having troubles as the module is working as expected now. If you are still have problems then contact me on the MagicMirror forum please
