### ISSUE TITLE
stuck in "hello mother earth"

### ISSUE THREAD

**Issue by IceT-max** [mykle1/MMM-EARTH#14]
I've same issue like in number 12.
Any ideas to check? Pay attention that I use the module from a remote server in cloud.

**Comment by mykle1** [comment]
I just downloaded and installed this fresh. It fires right up. No issues at all. Perhaps it has something to do with using it from a remote server in cloud. I'm not seeing anything wrong with the module and I can't help you regarding the server/cloud thing. Sorry.

**Comment by IceT-max** [comment]
A little help was appreciated.. like this I din't know what I can check.. umph.. in analogue situation other developer help with some ideas or check. Mhmm 😞
