### ISSUE TITLE
No image

### ISSUE THREAD

**Issue by JohnB7777** [mykle1/MMM-EARTH#7]
Hello,

I have a problem : since about one week, there is no more image of the earth displayed by the screen.
Instead, there is a bar.
How can I fix that ?

Thank you !

**Comment by cowboysdude** [comment]
All fixed now John.... get a fresh copy ;)

**Comment by mykle1** [comment]
NASA changed their data. The Module Doctor (cowboysdude) made a house call and remedied the situation. Thanks Bro! And thanks JohnB7777 for your interest

**Comment by JohnB7777** [comment]
Since today, it's not working again !
